@page
@node The Scheme shell (scsh)
@chapter The Scheme shell (scsh)

An incomplete port of the Scheme shell (scsh) is available for Guile
as a separate package.  The current status of guile-scsh can be found at
@url{http://arglist.com/guile/}.

For information about scsh see
@url{http://www-swiss.ai.mit.edu/ftpdir/scsh/}.

The closest emulation of scsh can be obtained by running:

@smalllisp
(load-from-path "scsh/init")
@end smalllisp

See the USAGE file supplied with guile-scsh for more details.
