@page
@node Libguile Intro
@chapter Using Guile as an Extension Language

The chapters in this part of the manual explain how to use Guile as a
powerful application extension language.

An important change for the 1.6.x series of Guile releases is that the
GH interface is now deprecated.  For the reasoning behind this decision,
see @xref{GH deprecation}.  The GH interface will continue to be
supported for the 1.6.x and 1.8.x release series, but will be dropped
thereafter, so developers are encouraged to switch progressively to the
scm interface.  The last chapter in this part of the manual (@pxref{GH})
documents both how to use GH and how to switch from GH to scm.

The documentation of the scm interface is currently a bit confused, but
the situation should improve rapidly once the 1.6.0 release is out.  The
plan is to refocus the bulk of Part II, currently ``Guile Scheme'', as
the ``Guile API Reference'' so that it covers both Scheme and C
interfaces.  (This makes sense because almost all of Guile's primitive
procedures on the Scheme level --- e.g. @code{memq} --- are also
available as C level primitives in the scm interface ---
e.g. @code{scm_memq}.)  There will then remain a certain amount of
Scheme-specific (such as the ``Basic Ideas'' chapter) and C-specific
documentation (such as SMOB usage and interaction with the garbage
collector) to collect into corresponding chapters.
