#!/bin/sh

# Choose a UTF-8 locale.  The locale doesn't have to be available on the
# system since `environ_locale_charset' does not actually try to set it.
LC_ALL="en_US.UTF-8"
export LC_ALL
unset LANG
unset LC_CTYPE

exec guile -q -s "$0" "λ"
!#

;; Make sure our first argument is a lower-case lambda.
;;
;; Up to Guile 2.0.3 included, command-line arguments would not be converted
;; according to the locale settings; see
;; <http://lists.gnu.org/archive/html/guile-devel/2011-11/msg00026.html> for
;; details.
(exit (string=? (cadr (program-arguments)) "λ"))

;; Local Variables:
;; mode: scheme
;; coding: utf-8
;; End:
